name: Bug Report
description: Report an issue or unexpected behavior
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: checkboxes
    attributes:
      label: Guidelines
      options:
        - label: I have searched the issue tracker for similar issues.
          required: false
  - type: input
    attributes:
      label: Operating system
    validations:
      required: false
  - type: textarea
    attributes:
      label: Bug description
      description: |
        You can include screenshots or log files.
    validations:
      required: false
