name: CI on PR

on:
  workflow_dispatch:
  pull_request:
    branches: [ "*" ]

env:
  JAVA_VERSION: '23'

jobs:
  gradle-test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run tests
        run: |
          ./gradlew test --stacktrace
      - name: Upload test logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-test-results
          path: |
            **/build/reports/
            **/build/test-results/


