name: Draft release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download candidate artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded
          pattern: MRT-*
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: Draft release
          files: downloaded/**
